pipeline {
    agent any
    tools {
        nodejs 'nodejs-23-6'
    }
    environment {
        MONGOURI="mongodb+srv://cluster0.awxhn.mongodb.net/retryWrites=true&w=majority"
        MONGO_USER="sai"
        MONGO_PASSWORD="secret32412"
        PORT=2121
        SONAR_SCANNER_HOME = tool 'sonarqube-scanner-621'
    }

    options {
        disableResume()
        disableConcurrentBuilds abortPrevious: true
    }

    stages {
        // This stage can be avoided as we directly used Pipelinescript from SCM
        // stage('Git Checkout') {
        //     steps {
        //         git branch: 'pre-prod', url: 'https://github.com/iam-narasimhasai/GoalsApp'
        //     }
        // }

        stage('Installing Dependencies') {
            options { timestamps() }
            steps {
                sh '''
                    cd backend
                    npm install
                '''
            }
        }

        stage('OWASP Dependency Check') {
            steps {
                dependencyCheck additionalArguments: '--scan backend/ --out backend/owasp-report --disableYarnAudit --prettyPrint --format ALL', 
                                nvdCredentialsId: 'NVD-API-KEY', 
                                odcInstallation: 'OWASP-DepCheck-12'

                // Uncomment to publish results and fail the build for critical vulnerabilities
                // dependencyCheckPublisher failedTotalCritical: 1, pattern: 'backend/owasp-report/dependency-check-report.xml', stopBuild: true
            }
        }

        stage('Run Unit Testing') {
            options { retry(3) }
            steps {
                sh '''
                    cd backend
                    npm run test
                '''
            }
        }

        stage('Code Coverage') {
            steps {
                catchError(message: 'Oops! it will be fixed in future', stageResult: 'UNSTABLE') {
                    sh '''
                        cd backend
                        npm run coverage
                    '''
                }
            }
        }

        stage('SAST - SonarQube') {
            steps {
                timeout(time: 60, unit: 'SECONDS') {
                    withSonarQubeEnv('sonar-qube-server') {
                        sh '''
                            cd backend/
                            echo $SONAR_SCANNER_HOME

                            $SONAR_SCANNER_HOME/bin/sonar-scanner \
                                -Dsonar.projectKey=GoalsApp \
                                -Dsonar.sources=app.js \
                                -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
                        '''
                    }
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Build Docker Image') {
            steps{
        
                sh '''
                cd backend/
                printenv
                docker build -t narasimhasai9581/testingbackend:${GIT_COMMIT} .
                '''



            }

        }
stage('Trivy Vulnerability Scanner') {
    steps {
        sh '''
        cd backend/
        
        # Run Trivy for LOW, MEDIUM, and HIGH severities
        trivy image --severity LOW,MEDIUM,HIGH \
                    --exit-code 0 \
                    --quiet \
                    --format json \
                    -o trivy-image-MEDIUM-results.json \
                    narasimhasai9581/testingbackend:${GIT_COMMIT}

        # Run Trivy for CRITICAL severities
        trivy image --severity CRITICAL \
                    --exit-code 1 \
                    --quiet \
                    --format json \
                    -o trivy-image-CRITICAL-results.json \
                    narasimhasai9581/testingbackend:${GIT_COMMIT}
        '''
    }
}




















    }

    post {
        always {
            publishHTML([
                allowMissing: true, 
                alwaysLinkToLastBuild: true, 
                keepAll: true, 
                reportDir: 'backend/owasp-report', 
                reportFiles: 'dependency-check-jenkins.html', 
                reportName: 'Dependency HTML Report', 
                reportTitles: '', 
                useWrapperFileDirectly: true
            ])

            junit allowEmptyResults: true, keepProperties: true, stdioRetention: '', testResults: 'backend/test-results.xml'

            publishHTML([
                allowMissing: true, 
                alwaysLinkToLastBuild: true, 
                keepAll: true, 
                reportDir: 'backend/coverage/lcov-report', 
                reportFiles: 'index.html', 
                reportName: 'Code Coverage HTML Report', 
                reportTitles: '', 
                useWrapperFileDirectly: true
            ])
        }
    }
}